Repository meowl-surveillance-system/meowl, pull requests merged in 2020-04, with the labels that each got.

#68 Add catch to function retrieveVideo
  src/web/client/src/components/Playback/Playback.tsx
Labels: enhancement

#46 Add face recognition
  src/cv/app.py
  src/cv/apply_detections.py
  src/cv/cv_producer.py
  src/cv/embedding_extractor.py
  src/cv/insert_frame.py
  src/cv/recognize_faces.py
  src/cv/requirements.txt
  src/cv/retrieve_face_resources.sh
  src/cv/run_app.sh
  src/cv/run_test.sh
  src/cv/settings.py
  src/cv/test_apply_detections.py
  src/cv/test_embedding_extract.py
  src/cv/test_object_detector.py
  src/cv/test_recognize_face.py
  src/cv/test_train_face.py
  src/cv/tests.py
  src/cv/train_face_recognizer.py
  src/cv/yolo_video_detect.py
  src/db/cass/create_db.py
Labels: enhancement

#71 Remove scripts folder and place installation scripts to their respective apps
  scripts/README.md
  scripts/check
  scripts/lib/install_mobile_dev.sh
  scripts/run
  src/api/.gitignore
  src/camera/mobile/install
  src/camera/pi/install
  src/config/.gitignore
  src/cv/install
  src/db/cass/install
  src/install
  src/lib/cassandra/install
  src/lib/kafka/install
  src/lib/kube/deployment.yaml
  src/lib/kube/install
  src/lib/kube/local-volumes.yaml
  src/lib/kube/run-kubernetes
  src/lib/kube/service-cassandra.yaml
  src/lib/kube/statefulset-cassandra.yaml
  src/lib/nginx-rtmp/install
  src/notifications/install
  src/web/install
Labels: enhancement

#41 Add http status code based authentication for rtmp and hls
  src/lib/nginx-rtmp/install
Labels: enhancement

#73 Add documentations
  src/web/client/src/components/LiveStream/LiveStream.tsx
  src/web/client/src/components/Login/Login.tsx
  src/web/client/src/components/Navbar/Navbar.tsx
  src/web/client/src/components/Playback/Playback.tsx
  src/web/client/src/components/ProtectedRoute/ProtectedRoute.tsx
  src/web/client/src/components/Register/Register.tsx
  src/web/client/src/components/ResponsivePlayer/ResponsivePlayer.tsx
Labels: documentation

#76 Automate uploading dataset resources
  src/cv/add_dataset_resources.py
  src/cv/app.py
  src/cv/insert_frame.py
  src/cv/settings.py
  src/db/cass/create_db.py
Labels: enhancement

#78 Admin backend
  src/db/cass/create_db.py
  src/web/server/app/controllers/auth.ts
  src/web/server/app/middlewares/authChecks.ts
  src/web/server/app/routes/auth.ts
  src/web/server/app/services/auth.ts
  src/web/server/app/tests/controllers/auth.test.ts
  src/web/server/app/tests/middlewares/authChecks.test.ts
  src/web/server/app/tests/services/auth.test.ts
  src/web/server/app/utils/queries.ts
Labels: enhancement

#86 Add admin credentials
  src/db/cass/Dockerfile
  src/db/cass/create_db.py
  src/db/cass/requirements.txt
  src/db/cass/settings.py
Labels: enhancement

#87 Run gts fix on web backend
  src/web/server/app/controllers/auth.ts
  src/web/server/app/index.ts
  src/web/server/app/utils/client.ts
  src/web/server/app/utils/settings.ts
Labels: enhancement

#92 Add admin check route
  src/web/server/app/controllers/auth.ts
  src/web/server/app/routes/auth.ts
  src/web/server/app/tests/controllers/auth.test.ts
Labels: enhancement

#94 Get all pending accounts
  src/web/server/app/controllers/auth.ts
  src/web/server/app/routes/auth.ts
  src/web/server/app/services/auth.ts
  src/web/server/app/tests/controllers/auth.test.ts
  src/web/server/app/tests/services/auth.test.ts
  src/web/server/app/utils/queries.ts
Labels: enhancement

#88 Add password reset feature
  src/db/cass/create_db.py
  src/web/server/app/controllers/auth.ts
  src/web/server/app/middlewares/authChecks.ts
  src/web/server/app/routes/auth.ts
  src/web/server/app/services/auth.ts
  src/web/server/app/tests/controllers/auth.test.ts
  src/web/server/app/tests/middlewares/authChecks.test.ts
  src/web/server/app/tests/services/auth.test.ts
  src/web/server/app/utils/mailer.ts
  src/web/server/app/utils/queries.ts
  src/web/server/app/utils/settings.ts
  src/web/server/package-lock.json
  src/web/server/package.json
Labels: enhancement

#93 Account approval/rejection frontend
  src/web/client/src/App.tsx
  src/web/client/src/components/AdminRoute/AdminRoute.test.tsx
  src/web/client/src/components/AdminRoute/AdminRoute.tsx
  src/web/client/src/components/AdminRoute/__snapshots__/AdminRoute.test.tsx.snap
  src/web/client/src/components/Login/Login.test.tsx
  src/web/client/src/components/Login/Login.tsx
  src/web/client/src/components/Navbar/Navbar.test.tsx
  src/web/client/src/components/Navbar/Navbar.tsx
  src/web/client/src/components/PendingAccounts/PendingAccounts.test.tsx
  src/web/client/src/components/PendingAccounts/PendingAccounts.tsx
  src/web/client/src/components/PendingAccounts/__snapshots__/PendingAccounts.test.tsx.snap
  src/web/client/src/components/Register/Register.tsx
  src/web/server/app/controllers/auth.ts
  src/web/server/app/routes/auth.ts
  src/web/server/app/services/auth.ts
  src/web/server/app/tests/controllers/auth.test.ts
  src/web/server/app/tests/services/auth.test.ts
  src/web/server/app/utils/queries.ts
Labels: enhancement

#96 Modify Register component
  src/web/client/src/App.tsx
  src/web/client/src/components/Register/Register.test.tsx
  src/web/client/src/components/Register/Register.tsx
  src/web/client/src/components/Register/__snapshots__/Register.test.tsx.snap
Labels: enhancement

#89 Add nginx hls ip and port to client and add flag for https in nginx
  src/lib/nginx-rtmp/Dockerfile
  src/lib/nginx-rtmp/README.md
  src/lib/nginx-rtmp/install
  src/web/Dockerfile
  src/web/client/src/components/LiveStream/LiveStream.tsx
  src/web/client/src/settings.tsx
  src/web/server/app/index.ts
  src/web/server/app/utils/settings.ts
Labels: bug, enhancement

#97 Add AccountRecovery and PasswordReset components
  src/web/client/src/App.tsx
  src/web/client/src/components/AccountRecovery/AccountRecovery.test.tsx
  src/web/client/src/components/AccountRecovery/AccountRecovery.tsx
  src/web/client/src/components/AccountRecovery/__snapshots__/AccountRecovery.test.tsx.snap
  src/web/client/src/components/Login/Login.tsx
  src/web/client/src/components/PasswordReset/PasswordReset.test.tsx
  src/web/client/src/components/PasswordReset/PasswordReset.tsx
  src/web/client/src/components/PasswordReset/__snapshots__/PasswordReset.test.tsx.snap
  src/web/server/app/controllers/auth.ts
  src/web/server/app/routes/auth.ts
  src/web/server/app/services/auth.ts
  src/web/server/app/tests/controllers/auth.test.ts
  src/web/server/app/utils/queries.ts
Labels: enhancement
